# Generated by Django 5.2.16 on 2026-07-31 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Pinned past accounts.0004 rather than left on the autodetector's
        # __first__ swappable dependency: Capture.owner points at User's
        # numeric primary key, which only exists from 0004 onwards. Without
        # this, rewinding accounts below 0004 (which accounts'
        # migration tests do) would leave capture_capture behind pointing
        # at a column that no longer exists.
        ('accounts', '0004_numeric_user_primary_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['owner', 'resolved_at', '-created_at'], name='capture_owner_inbox_idx')],
            },
        ),
    ]
