# Generated by Django 5.2.16 on 2026-08-01 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
        ('lists', '0021_item_always_recurs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='promoted_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lists.item'),
        ),
        migrations.AddField(
            model_name='capture',
            name='resolution',
            field=models.CharField(blank=True, choices=[('task', 'Task'), ('idea', 'Idea'), ('discarded', 'Discarded')], max_length=20),
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('exploring', 'Exploring'), ('reference', 'Reference'), ('promoted', 'Promoted')], default='exploring', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
                ('promoted_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lists.item')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='capture',
            name='promoted_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capture.idea'),
        ),
    ]
