# Generated by Django 5.2.16 on 2026-08-02 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0003_capture_idempotency_key'),
        ('lists', '0024_alter_item_commitment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='idea_owner_status_idx'),
        ),
    ]
