# Generated by Django 5.2.16 on 2026-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_idea_idea_owner_status_idx'),
        ('lists', '0031_commitment_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='captures', to='lists.tag'),
        ),
    ]
