# Generated by Django 5.2.16 on 2026-08-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0005_capture_tags'),
        ('lists', '0031_commitment_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='lists.tag'),
        ),
    ]
