# Generated by Django 5.2.16 on 2026-08-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0006_idea_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='related_ideas',
            field=models.ManyToManyField(blank=True, to='capture.idea'),
        ),
    ]
