# Generated by Django 5.2.16 on 2026-08-02 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Pinned to the numeric-primary-key migration, not just the
        # swappable dependency the autodetector writes. swappable_dependency
        # resolves to accounts' *initial* migration, so it leaves these
        # tables standing while accounts rewinds past 0004 -- and SQLite
        # then fails the rebuild with "foreign key mismatch -
        # routines_routine referencing accounts_user".
        #
        # The third app to need this line: lists/0011 pinned it when the
        # swap happened, daily/0001 rediscovered it the hard way, and this
        # one was written knowing. Any new app with an FK to User needs it.
        ("accounts", "0004_numeric_user_primary_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cadence', models.CharField(choices=[('daily', 'Every day'), ('weekly', 'Every week')], default='daily', max_length=10)),
                ('target_quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoutineOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('target_quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='open', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_occurrences', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='routines.routine')),
            ],
            options={
                'ordering': ('period_start', 'id'),
                'indexes': [models.Index(fields=['owner', 'period_start'], name='routine_owner_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('routine', 'period_start'), name='unique_routine_occurrence_period')],
            },
        ),
    ]
