# Generated by Django 5.2.16 on 2026-08-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
