# Generated by Django 5.2.16 on 2026-08-02 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_routine_paused_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutinePause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_at', models.DateTimeField()),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_pauses', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='routines.routine')),
            ],
            options={
                'ordering': ('paused_at', 'id'),
                'indexes': [models.Index(fields=['owner', 'paused_at'], name='routine_pause_owner_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resumed_at__isnull', True)), fields=('routine',), name='one_open_pause_per_routine')],
            },
        ),
    ]
