# Generated by Django 5.2.16 on 2026-08-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_seed_open_pauses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineoccurrence',
            name='outcome',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('partial', 'Enough')], default='open', max_length=10),
        ),
    ]
