# Generated by Django 5.2.16 on 2026-08-02 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Pinned to the numeric-primary-key migration, not just the
        # swappable dependency the autodetector wrote. swappable_dependency
        # resolves to accounts' *initial* migration, which leaves this table
        # standing while accounts rewinds past 0004 -- and SQLite then fails
        # the rebuild with "foreign key mismatch - daily_dailyentry
        # referencing accounts_user", because owner_id no longer points at a
        # unique column. lists/0011 pins it for the same reason; that is why
        # accounts' own migration tests could rewind before this app existed.
        ("accounts", "0004_numeric_user_primary_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intentions', models.TextField(blank=True, default='')),
                ('gratitude', models.TextField(blank=True, default='')),
                ('happenings', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('owner', 'date'), name='unique_daily_entry_per_owner_date')],
            },
        ),
    ]
