# Generated by Django 5.2.16 on 2026-08-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
        ('lists', '0024_alter_item_commitment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus', to='daily.dailyentry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_focus', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lists.item')),
            ],
            options={
                'verbose_name_plural': 'daily focus',
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('entry', 'task'), name='unique_daily_focus_per_entry_task')],
            },
        ),
    ]
