# Generated by Django 5.2.16 on 2026-08-20 04:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_dailyfocus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='search_document',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('intentions', 'gratitude', 'happenings', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='daily_entry_search'),
        ),
    ]
