# Generated by Django 5.2.16 on 2026-08-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_dailyentry_search_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfocus',
            name='accepted_from_draft',
            field=models.BooleanField(default=False),
        ),
    ]
