# Generated by Django 5.2.17 on 2026-09-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_dailyfocus_accepted_from_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='list_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
