/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["clarice_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Navigation
         * @description Everything the persistent side nav needs, on every page.
         *
         *     A single endpoint rather than three payloads each growing the same
         *     fields: the agenda already carried list summaries, but the list page and
         *     archive didn't, and duplicating them into both schemas would mean three
         *     places to keep in step.
         */
        get: operations["lists_api_v1_navigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agenda */
        get: operations["lists_api_v1_agenda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lists/{list_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Detail */
        get: operations["lists_api_v1_list_detail"];
        put?: never;
        post?: never;
        /** Delete List */
        delete: operations["lists_api_v1_delete_list"];
        options?: never;
        head?: never;
        /** Rename List */
        patch: operations["lists_api_v1_rename_list"];
        trace?: never;
    };
    "/api/v1/tasks/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Detail */
        get: operations["lists_api_v1_task_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Archive */
        get: operations["lists_api_v1_archive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Out
         * @description End the session the SPA is holding.
         *
         *     An endpoint rather than a logout form copied into React: the typed
         *     client already sends X-CSRFToken on non-GET requests, Django's own
         *     logout() keeps its session-invalidation and session-key-cycling
         *     behaviour, and the SPA gets a definite success before it throws away
         *     its cached queries and navigates.
         *
         *     POST only, and CSRF-checked by the session auth the whole router uses,
         *     so a cross-site request cannot log someone out as a nuisance.
         */
        post: operations["accounts_api_v1_log_out"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Time Zones
         * @description The zones the picker may offer.
         *
         *     Served rather than read from the browser's own Intl list: the two can
         *     disagree, and a disagreement would show up as a validation error on a
         *     zone this application had just offered the person.
         */
        get: operations["accounts_api_v1_list_time_zones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["accounts_api_v1_get_preferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Preferences */
        patch: operations["accounts_api_v1_update_preferences"];
        trace?: never;
    };
    "/api/v1/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Capture */
        post: operations["capture_api_v1_new_capture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["daily_api_v1_get_today"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/day/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Day */
        get: operations["daily_api_v1_get_day"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Write Day
         * @description Write into the requesting user's day.
         *
         *     There is no ownership check to forget: the entry is addressed by
         *     (request.user, day), so the path names a date and never a record. One
         *     person cannot reach another's day through this endpoint at all, which
         *     is a smaller surface than an id would be.
         */
        patch: operations["daily_api_v1_write_day"];
        trace?: never;
    };
    "/api/v1/day/{day}/focus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pin To Day
         * @description Choose a task as work for this day.
         *
         *     Returns the whole day rather than the one pin: the client has to
         *     re-render the focus list and the action items together anyway, and one
         *     response keeps them from disagreeing for a frame.
         */
        post: operations["daily_api_v1_pin_to_day"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/day/{day}/focus/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unpin From Day
         * @description Take a task off this day, keeping the record that it was chosen.
         */
        delete: operations["daily_api_v1_unpin_from_day"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Routine Standings */
        get: operations["routines_api_v1_routine_standings"];
        put?: never;
        /** New Routine */
        post: operations["routines_api_v1_new_routine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/{routine_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Routine
         * @description Add to the current period, returning every standing rather than one.
         *
         *     The Daily Page renders them together, so one response keeps the list
         *     from disagreeing with itself for a frame -- the same reason the day's
         *     focus endpoints answer with the whole day.
         *
         *     A negative amount is a correction, which is deliberately this endpoint
         *     rather than one of its own: fixing a mis-tap is the same kind of
         *     statement as making one, and a separate route would invite a separate
         *     rule. Correcting a period nobody has logged is a no-op, so the response
         *     is the unchanged standings rather than an error about a row that ought
         *     not to exist.
         */
        post: operations["routines_api_v1_log_routine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/{routine_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Routine
         * @description Record that this period was deliberately not done.
         *
         *     Its own route rather than a flag on the log endpoint, because it is a
         *     different statement: logging says what happened, skipping says what was
         *     decided. Collapsing them would be the near-identical-controls problem
         *     C2 found in the task UI, one layer down.
         */
        post: operations["routines_api_v1_skip_routine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** MeOut */
        MeOut: {
            /** Username */
            username: string;
            /** Email */
            email: string;
        };
        /** NavListOut */
        NavListOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Open Count */
            open_count: number;
            /** Overdue Count */
            overdue_count: number;
            /**
             * Color Key
             * @enum {string}
             */
            color_key: "sky" | "sage" | "amber" | "lilac" | "coral" | "azure" | "blush" | "straw";
        };
        /** NavOut */
        NavOut: {
            /** Lists */
            lists: components["schemas"]["NavListOut"][];
            /** Archived Count */
            archived_count: number;
            /** Inbox Count */
            inbox_count: number;
            /** Settings Url */
            settings_url: string;
            /** Inbox Url */
            inbox_url: string;
            /** Ideas Url */
            ideas_url: string;
            /** Landing Surface */
            landing_surface: string;
        };
        /** AgendaBucketOut */
        AgendaBucketOut: {
            /**
             * Key
             * @enum {string}
             */
            key: "overdue" | "today" | "week" | "later" | "someday";
            /** Label */
            label: string;
            /** Collapsed */
            collapsed: boolean;
        };
        /** AgendaListSummaryOut */
        AgendaListSummaryOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Create Item Url */
            create_item_url: string;
            /** Open Count */
            open_count: number;
            /** Overdue Count */
            overdue_count: number;
            /**
             * Color Key
             * @enum {string}
             */
            color_key: "sky" | "sage" | "amber" | "lilac" | "coral" | "azure" | "blush" | "straw";
        };
        /** AgendaOut */
        AgendaOut: {
            /** Today */
            today: string;
            /** Username */
            username: string;
            /** Archive Url */
            archive_url: string;
            /** Archived Count */
            archived_count: number;
            /** New List Url */
            new_list_url: string;
            /** Settings Url */
            settings_url: string;
            /** Daily Digest */
            daily_digest: boolean;
            /** Buckets */
            buckets: components["schemas"]["AgendaBucketOut"][];
            /** Items */
            items: components["schemas"]["TaskOut"][];
            /** Completed Today */
            completed_today: components["schemas"]["TaskOut"][];
            /** Lists */
            lists: components["schemas"]["AgendaListSummaryOut"][];
        };
        /** SubtaskCountsOut */
        SubtaskCountsOut: {
            /** Total */
            total: number;
            /** Done */
            done: number;
        };
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "archived";
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Archived At */
            archived_at: string | null;
            /** Due Date */
            due_date: string | null;
            /** Position */
            position: number;
            /** Tags */
            tags: string[];
            /**
             * Recurrence
             * @enum {string}
             */
            recurrence: "none" | "daily" | "weekly" | "monthly";
            /** Notes */
            notes: string;
            parent: components["schemas"]["TaskParentOut"] | null;
            /** Always Recurs */
            always_recurs: boolean;
            subtask_counts: components["schemas"]["SubtaskCountsOut"];
            /** List Id */
            list_id: number;
            /** Url */
            url: string;
            /** Edit Url */
            edit_url: string;
        };
        /** TaskParentOut */
        TaskParentOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
        };
        /** ListDetailOut */
        ListDetailOut: {
            list: components["schemas"]["ListRefOut"];
            /** Items */
            items: components["schemas"]["TaskOut"][];
            /** Archived Count */
            archived_count: number;
            /** Archive Url */
            archive_url: string;
        };
        /** ListRefOut */
        ListRefOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Create Item Url */
            create_item_url: string;
            /** Reorder Url */
            reorder_url: string;
        };
        /** ListRenameIn */
        ListRenameIn: {
            /** Title */
            title: string;
        };
        /** TaskDetailOut */
        TaskDetailOut: {
            task: components["schemas"]["TaskOut"];
            list: components["schemas"]["TaskListSummaryOut"];
            /** Subtasks */
            subtasks: components["schemas"]["TaskOut"][];
        };
        /** TaskListSummaryOut */
        TaskListSummaryOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** ArchiveOut */
        ArchiveOut: {
            /** Items */
            items: components["schemas"]["TaskOut"][];
            /** Lists */
            lists: components["schemas"]["TaskListSummaryOut"][];
        };
        /** TimeZonesOut */
        TimeZonesOut: {
            /** Time Zones */
            time_zones: string[];
        };
        /** PreferencesOut */
        PreferencesOut: {
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Daily Digest */
            daily_digest: boolean;
            /**
             * Theme
             * @enum {string}
             */
            theme: "system" | "light" | "dark";
            /** Time Zone */
            time_zone: string;
            /**
             * Compass Purpose
             * @default
             */
            compass_purpose: string;
            /**
             * Compass Question
             * @default
             */
            compass_question: string;
            /**
             * Landing Surface
             * @default day
             * @enum {string}
             */
            landing_surface: "day" | "agenda";
        };
        /** PreferencesIn */
        PreferencesIn: {
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Daily Digest */
            daily_digest: boolean;
            /**
             * Theme
             * @enum {string}
             */
            theme: "system" | "light" | "dark";
            /** Time Zone */
            time_zone: string;
            /**
             * Compass Purpose
             * @default
             */
            compass_purpose: string;
            /**
             * Compass Question
             * @default
             */
            compass_question: string;
            /**
             * Landing Surface
             * @default day
             * @enum {string}
             */
            landing_surface: "day" | "agenda";
        };
        /** CaptureOut */
        CaptureOut: {
            /** Id */
            id: number;
            /** Created At */
            created_at: string;
        };
        /** CaptureIn */
        CaptureIn: {
            /** Text */
            text: string;
        };
        /** DayOut */
        DayOut: {
            /** Date */
            date: string;
            /** Intentions */
            intentions: string;
            /** Gratitude */
            gratitude: string;
            /** Happenings */
            happenings: string;
            /** Today */
            today: string;
            /** Action Items */
            action_items: components["schemas"]["TaskOut"][];
            /** Shows Action Items */
            shows_action_items: boolean;
            /** Focus */
            focus: components["schemas"]["FocusOut"][];
            /** Compass Purpose */
            compass_purpose: string;
            /** Compass Question */
            compass_question: string;
            /** Routines */
            routines: components["schemas"]["StandingOut"][];
            /** Routines Are Loggable */
            routines_are_loggable: boolean;
        };
        /**
         * FocusOut
         * @description A pinned task, as the day needs to render it.
         *
         *     Not TaskOut: a focus row is a different statement from an agenda row,
         *     and the fields that differ are the point. `selected_at` says when the
         *     choice was made, and `task_id` is nullable because a task can be
         *     permanently deleted while the record of having planned it survives.
         */
        FocusOut: {
            /** Task Id */
            task_id: number | null;
            /** Text */
            text: string;
            /** Status */
            status: string | null;
            /** Due Date */
            due_date: string | null;
            parent: components["schemas"]["TaskParentOut"] | null;
            /** Selected At */
            selected_at: string;
        };
        /** StandingOut */
        StandingOut: {
            /** Routine Id */
            routine_id: number;
            /** Title */
            title: string;
            /** Cadence */
            cadence: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /** Progress */
            progress: number;
            /** Target */
            target: number;
            /** Unit */
            unit: string;
            /** Outcome */
            outcome: string;
            /** Is Met */
            is_met: boolean;
        };
        /**
         * DayIn
         * @description Every field optional, and absent is not the same as empty.
         *
         *     The page may save one section without carrying the other two, so a
         *     field left out keeps its stored value -- see services.write_entry.
         */
        DayIn: {
            /** Intentions */
            intentions?: string | null;
            /** Gratitude */
            gratitude?: string | null;
            /** Happenings */
            happenings?: string | null;
        };
        /** FocusIn */
        FocusIn: {
            /** Task Id */
            task_id: number;
        };
        /** StandingsOut */
        StandingsOut: {
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Standings */
            standings: components["schemas"]["StandingOut"][];
        };
        /** RoutineIn */
        RoutineIn: {
            /** Title */
            title: string;
            /**
             * Cadence
             * @default daily
             */
            cadence: string;
            /**
             * Target Quantity
             * @default 1
             */
            target_quantity: number;
            /**
             * Unit
             * @default
             */
            unit: string;
        };
        /** LogIn */
        LogIn: {
            /**
             * Amount
             * @default 1
             */
            amount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    clarice_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    lists_api_v1_navigation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavOut"];
                };
            };
        };
    };
    lists_api_v1_agenda: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgendaOut"];
                };
            };
        };
    };
    lists_api_v1_list_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDetailOut"];
                };
            };
        };
    };
    lists_api_v1_delete_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lists_api_v1_rename_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListRenameIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRefOut"];
                };
            };
        };
    };
    lists_api_v1_task_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailOut"];
                };
            };
        };
    };
    lists_api_v1_archive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveOut"];
                };
            };
        };
    };
    accounts_api_v1_log_out: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_v1_list_time_zones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeZonesOut"];
                };
            };
        };
    };
    accounts_api_v1_get_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
        };
    };
    accounts_api_v1_update_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
        };
    };
    capture_api_v1_new_capture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
        };
    };
    daily_api_v1_get_today: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
        };
    };
    daily_api_v1_get_day: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
        };
    };
    daily_api_v1_write_day: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
        };
    };
    daily_api_v1_pin_to_day: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FocusIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
        };
    };
    daily_api_v1_unpin_from_day: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
        };
    };
    routines_api_v1_routine_standings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsOut"];
                };
            };
        };
    };
    routines_api_v1_new_routine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsOut"];
                };
            };
        };
    };
    routines_api_v1_log_routine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsOut"];
                };
            };
        };
    };
    routines_api_v1_skip_routine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsOut"];
                };
            };
        };
    };
}
