/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["clarice_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Navigation
         * @description Everything the persistent side nav needs, on every page.
         *
         *     A single endpoint rather than three payloads each growing the same
         *     fields: the agenda already carried list summaries, but the list page and
         *     archive didn't, and duplicating them into both schemas would mean three
         *     places to keep in step.
         */
        get: operations["lists_api_v1_navigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agenda */
        get: operations["lists_api_v1_agenda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lists/{list_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Detail */
        get: operations["lists_api_v1_list_detail"];
        put?: never;
        post?: never;
        /** Delete List */
        delete: operations["lists_api_v1_delete_list"];
        options?: never;
        head?: never;
        /** Rename List */
        patch: operations["lists_api_v1_rename_list"];
        trace?: never;
    };
    "/api/v1/tasks/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Detail */
        get: operations["lists_api_v1_task_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Archive */
        get: operations["lists_api_v1_archive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["accounts_api_v1_get_preferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Preferences */
        patch: operations["accounts_api_v1_update_preferences"];
        trace?: never;
    };
    "/api/v1/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Capture */
        post: operations["capture_api_v1_new_capture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** MeOut */
        MeOut: {
            /** Username */
            username: string;
            /** Email */
            email: string;
        };
        /** NavListOut */
        NavListOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Open Count */
            open_count: number;
            /** Overdue Count */
            overdue_count: number;
            /**
             * Color Key
             * @enum {string}
             */
            color_key: "sky" | "sage" | "amber" | "lilac" | "coral" | "azure" | "blush" | "straw";
        };
        /** NavOut */
        NavOut: {
            /** Lists */
            lists: components["schemas"]["NavListOut"][];
            /** Archived Count */
            archived_count: number;
            /** Inbox Count */
            inbox_count: number;
            /** Settings Url */
            settings_url: string;
            /** Inbox Url */
            inbox_url: string;
            /** Ideas Url */
            ideas_url: string;
        };
        /** AgendaBucketOut */
        AgendaBucketOut: {
            /**
             * Key
             * @enum {string}
             */
            key: "overdue" | "today" | "week" | "later" | "someday";
            /** Label */
            label: string;
            /** Collapsed */
            collapsed: boolean;
        };
        /** AgendaListSummaryOut */
        AgendaListSummaryOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Create Item Url */
            create_item_url: string;
            /** Open Count */
            open_count: number;
            /** Overdue Count */
            overdue_count: number;
            /**
             * Color Key
             * @enum {string}
             */
            color_key: "sky" | "sage" | "amber" | "lilac" | "coral" | "azure" | "blush" | "straw";
        };
        /** AgendaOut */
        AgendaOut: {
            /** Today */
            today: string;
            /** Username */
            username: string;
            /** Archive Url */
            archive_url: string;
            /** Archived Count */
            archived_count: number;
            /** New List Url */
            new_list_url: string;
            /** Settings Url */
            settings_url: string;
            /** Daily Digest */
            daily_digest: boolean;
            /** Buckets */
            buckets: components["schemas"]["AgendaBucketOut"][];
            /** Items */
            items: components["schemas"]["TaskOut"][];
            /** Completed Today */
            completed_today: components["schemas"]["TaskOut"][];
            /** Lists */
            lists: components["schemas"]["AgendaListSummaryOut"][];
        };
        /** SubtaskCountsOut */
        SubtaskCountsOut: {
            /** Total */
            total: number;
            /** Done */
            done: number;
        };
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "archived";
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Archived At */
            archived_at: string | null;
            /** Due Date */
            due_date: string | null;
            /** Position */
            position: number;
            /** Tags */
            tags: string[];
            /**
             * Recurrence
             * @enum {string}
             */
            recurrence: "none" | "daily" | "weekly" | "monthly";
            /** Notes */
            notes: string;
            parent: components["schemas"]["TaskParentOut"] | null;
            /** Always Recurs */
            always_recurs: boolean;
            subtask_counts: components["schemas"]["SubtaskCountsOut"];
            /** List Id */
            list_id: number;
            /** Url */
            url: string;
            /** Edit Url */
            edit_url: string;
        };
        /** TaskParentOut */
        TaskParentOut: {
            /** Id */
            id: number;
            /** Text */
            text: string;
        };
        /** ListDetailOut */
        ListDetailOut: {
            list: components["schemas"]["ListRefOut"];
            /** Items */
            items: components["schemas"]["TaskOut"][];
            /** Archived Count */
            archived_count: number;
            /** Archive Url */
            archive_url: string;
        };
        /** ListRefOut */
        ListRefOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Create Item Url */
            create_item_url: string;
            /** Reorder Url */
            reorder_url: string;
        };
        /** ListRenameIn */
        ListRenameIn: {
            /** Title */
            title: string;
        };
        /** TaskDetailOut */
        TaskDetailOut: {
            task: components["schemas"]["TaskOut"];
            list: components["schemas"]["TaskListSummaryOut"];
            /** Subtasks */
            subtasks: components["schemas"]["TaskOut"][];
        };
        /** TaskListSummaryOut */
        TaskListSummaryOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** ArchiveOut */
        ArchiveOut: {
            /** Items */
            items: components["schemas"]["TaskOut"][];
            /** Lists */
            lists: components["schemas"]["TaskListSummaryOut"][];
        };
        /** PreferencesOut */
        PreferencesOut: {
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Daily Digest */
            daily_digest: boolean;
            /**
             * Theme
             * @enum {string}
             */
            theme: "system" | "light" | "dark";
        };
        /** PreferencesIn */
        PreferencesIn: {
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Daily Digest */
            daily_digest: boolean;
            /**
             * Theme
             * @enum {string}
             */
            theme: "system" | "light" | "dark";
        };
        /** CaptureOut */
        CaptureOut: {
            /** Id */
            id: number;
            /** Created At */
            created_at: string;
        };
        /** CaptureIn */
        CaptureIn: {
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    clarice_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    lists_api_v1_navigation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavOut"];
                };
            };
        };
    };
    lists_api_v1_agenda: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgendaOut"];
                };
            };
        };
    };
    lists_api_v1_list_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDetailOut"];
                };
            };
        };
    };
    lists_api_v1_delete_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lists_api_v1_rename_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListRenameIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRefOut"];
                };
            };
        };
    };
    lists_api_v1_task_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailOut"];
                };
            };
        };
    };
    lists_api_v1_archive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveOut"];
                };
            };
        };
    };
    accounts_api_v1_get_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
        };
    };
    accounts_api_v1_update_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
        };
    };
    capture_api_v1_new_capture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureOut"];
                };
            };
        };
    };
}
