# Generated by Django 5.2.16 on 2026-07-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_item_status_and_update_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
