# Generated by Django 5.2.16 on 2026-07-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0013_item_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('position', 'id')},
        ),
        migrations.AddField(
            model_name='item',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
