# Generated by Django 5.2.16 on 2026-07-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0015_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recurrence',
            field=models.CharField(choices=[('none', "Doesn't repeat"), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
