# Generated by Django 5.2.16 on 2026-07-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0016_item_recurrence'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='item_list_state_idx',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['list', 'status', 'due_date'], name='item_list_state_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', 'due_date'], name='item_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['list', 'status', 'completed_at'], name='item_list_state_completed_idx'),
        ),
    ]
