# Generated by Django 5.2.16 on 2026-07-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0020_item_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='always_recurs',
            field=models.BooleanField(default=True),
        ),
    ]
