# Generated by Django 5.2.16 on 2026-08-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0023_anchor_existing_recurring_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='occurrences', to='lists.recurringcommitment'),
        ),
    ]
