# Generated by Django 5.2.16 on 2026-08-03 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0024_alter_item_commitment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('carries_forward', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_steps', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_steps', to='lists.item')),
            ],
            options={
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['task', 'is_done'], name='step_task_done_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_done', False)), fields=('task', 'text'), name='unique_open_checklist_step_text', nulls_distinct=False)],
            },
        ),
    ]
