"""Give each RecurringCommitment the template half of rule 8.

recurring-commitment-vocabulary-plan.md slice 1, the expand step. Purely
additive: five optional fields, plus a backfill that seeds each existing
commitment from its most recent occurrence. Nothing reads them yet --
_spawn_next_occurrence still copies from the completed item, which slice 2
changes -- so this migration cannot alter behaviour.

The newest occurrence is the right seed because the template says what the
*next* one starts as, and the newest occurrence is what the commitment
currently is. Earlier occurrences keep their own text and tags untouched,
which is the whole point of the pair: crane-plan.md 3's acceptance example
requires June to still read "Pay rent" after September was renamed.

Reversible, and genuinely so -- dropping the columns loses only a copy of
data that still exists on the occurrences it was read from.
"""
# Generated by Django 5.2.16 on 2026-08-03 06:19

import django.db.models.deletion
from django.db import migrations, models


def seed_templates(apps, schema_editor):
    RecurringCommitment = apps.get_model("lists", "RecurringCommitment")
    Item = apps.get_model("lists", "Item")

    seeded = 0
    empty = 0
    for commitment in RecurringCommitment.objects.all():
        newest = (
            Item.objects.filter(commitment=commitment)
            .order_by("-created_at", "-id")
            .first()
        )
        if newest is None:
            # Not reachable through the application -- a commitment is only
            # ever created alongside an item -- but a migration should not
            # assume that of production data it has never seen.
            empty += 1
            continue
        commitment.text = newest.text
        commitment.list_id = newest.list_id
        commitment.cadence = newest.recurrence
        commitment.notes = newest.notes
        commitment.save(
            update_fields=("text", "list", "cadence", "notes"),
        )
        commitment.tags.set(newest.tags.all())
        seeded += 1

    print(f"commitment template backfill: seeded={seeded} empty={empty}")


def unseed(apps, schema_editor):
    """Nothing to undo: the columns themselves are dropped by the reverse of
    the AddField operations below, and every value they held still exists on
    the occurrence it was copied from.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0030_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringcommitment',
            name='cadence',
            field=models.CharField(choices=[('none', "Doesn't repeat"), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='recurringcommitment',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='lists.list'),
        ),
        migrations.AddField(
            model_name='recurringcommitment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recurringcommitment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='commitments', to='lists.tag'),
        ),
        migrations.AddField(
            model_name='recurringcommitment',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(seed_templates, unseed),
    ]
