# Generated by Django 5.2.16 on 2026-08-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0032_list_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='lists.list'),
        ),
    ]
