# Generated by Django 5.2.16 on 2026-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0036_a_task_belongs_to_a_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringcommitment',
            name='cadence_mode',
            field=models.CharField(choices=[('anchored', 'On a fixed schedule'), ('floating', 'A set time after it is done')], default='anchored', max_length=10),
        ),
    ]
