# Generated by Django 5.2.16 on 2026-08-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0037_commitment_cadence_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
    ]
