# Generated by Django 5.2.16 on 2026-08-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0038_project_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desired_outcome',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
