# Generated by Django 5.2.16 on 2026-08-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0040_item_search_document_item_item_search_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('none', 'No priority'), ('high', 'Pressing'), ('low', 'Whenever')], default='none', max_length=6),
        ),
        migrations.AddField(
            model_name='recurringcommitment',
            name='priority',
            field=models.CharField(choices=[('none', 'No priority'), ('high', 'Pressing'), ('low', 'Whenever')], default='none', max_length=6),
        ),
    ]
