# Generated by Django 5.2.16 on 2026-08-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0041_item_priority_recurringcommitment_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='recurrence',
            field=models.CharField(choices=[('none', "Doesn't repeat"), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annually')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringcommitment',
            name='cadence',
            field=models.CharField(choices=[('none', "Doesn't repeat"), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annually')], default='none', max_length=12),
        ),
    ]
