# Generated by Django 5.2.16 on 2026-08-20 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0042_alter_item_recurrence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payee', models.CharField(blank=True, default='', max_length=200)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='lists.item')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='bill_amount_not_negative')],
            },
        ),
    ]
