# Generated by Django 5.2.16 on 2026-08-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0043_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lead_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringcommitment',
            name='lead_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
