# Generated by Django 5.2.16 on 2026-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0044_item_lead_days_recurringcommitment_lead_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abandon_if',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
