# Generated by Django 5.2.16 on 2026-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0045_project_abandon_if_project_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='learned',
            field=models.TextField(blank=True, default=''),
        ),
    ]
