# Generated by Django 5.2.17 on 2026-08-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0046_project_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
