# Generated by Django 5.2.17 on 2026-08-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0049_account_balancereading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='paid_by',
        ),
    ]
