# Generated by Django 5.2.17 on 2026-08-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0050_remove_account_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='recurrence',
            field=models.CharField(choices=[('none', "Doesn't repeat"), ('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Every two weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annually')], default='none', max_length=12),
        ),
        migrations.AlterField(
            model_name='recurringcommitment',
            name='cadence',
            field=models.CharField(choices=[('none', "Doesn't repeat"), ('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Every two weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annually')], default='none', max_length=12),
        ),
    ]
