# Generated by Django 5.2.17 on 2026-08-27 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0051_alter_item_recurrence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('position', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AddField(
            model_name='moneyline',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='lists.moneycategory'),
        ),
        migrations.AddConstraint(
            model_name='moneycategory',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_money_category_per_owner'),
        ),
    ]
