# Generated by Django 5.2.17 on 2026-08-31 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0052_moneycategory_moneyline_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('direction', models.CharField(choices=[('out', 'Money out'), ('in', 'Money in')], default='out', max_length=3)),
                ('cadence', models.CharField(choices=[('none', "Doesn't repeat"), ('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Every two weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annually')], default='monthly', max_length=20)),
                ('cadence_mode', models.CharField(choices=[('anchored', 'On a fixed schedule'), ('floating', 'A set time after it is done')], default='anchored', max_length=20)),
                ('lead_days', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_series', to='lists.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_series', to='lists.moneycategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'bill series',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('payee', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('direction', models.CharField(choices=[('out', 'Money out'), ('in', 'Money in')], default='out', max_length=3)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='lists.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='lists.moneycategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='lists.billseries')),
            ],
        ),
        migrations.AddIndex(
            model_name='billseries',
            index=models.Index(fields=['owner', '-created_at'], name='bill_series_owner'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['owner', 'due_date'], name='bill_owner_due'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['owner', 'paid_at'], name='bill_owner_paid_at'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['series', 'due_date'], name='bill_series_due'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_amount__isnull', True), ('paid_at__isnull', True)), models.Q(('paid_amount__isnull', False), ('paid_at__isnull', False)), _connector='OR'), name='bill_paid_at_and_amount_agree'),
        ),
    ]
