# Generated by Django 5.2.17 on 2026-09-01 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0053_bill_and_bill_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bill',
            name='bill_paid_at_and_amount_agree',
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__isnull', True), ('paid_at__isnull', False), _connector='OR'), name='bill_paid_at_and_amount_agree'),
        ),
    ]
