# Generated by Django 5.2.17 on 2026-09-01 00:40

from django.db import migrations, models


def carry_lead_days_over(apps, schema_editor):
    """Backfill from the task each bill was converted from.

    `0055` could not set what the model did not have. Matching on owner, payee
    and due date rather than keeping a key: the conversion is one-to-one and
    those three identify a row, and adding a temporary column to carry a
    pointer would outlive its purpose.
    """
    Bill = apps.get_model("lists", "Bill")
    MoneyLine = apps.get_model("lists", "MoneyLine")
    by_key = {
        (line.item.owner_id, line.payee, line.item.due_date): line.item.lead_days
        for line in MoneyLine.objects.select_related("item")
    }
    for bill in Bill.objects.all():
        lead = by_key.get((bill.owner_id, bill.payee, bill.due_date))
        if lead:
            bill.lead_days = lead
            bill.save(update_fields=["lead_days"])


def forget_lead_days(apps, schema_editor):
    """Nothing to undo: the column goes with the reverse of the AddField
    below, and every value in it came from the function above."""


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0055_copy_money_lines_into_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='lead_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(carry_lead_days_over, forget_lead_days),
    ]
