# Generated by Django 5.2.17 on 2026-09-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0061_money_models_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kept_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
