# Generated by Django 5.2.16 on 2026-08-02 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Pinned to the numeric-primary-key migration rather than left to
        # the swappable dependency the autodetector writes, which resolves
        # to accounts' *initial* migration and leaves this table standing
        # while accounts rewinds past 0004 -- SQLite then fails the rebuild
        # with "foreign key mismatch - review_weeklyreview referencing
        # accounts_user".
        #
        # The fourth app to need this line, after lists/0011, daily/0001 and
        # routines/0001. Any new app with an FK to User needs it.
        ("accounts", "0004_numeric_user_primary_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('reflections', models.TextField(blank=True, default='')),
                ('plan', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_planned_total', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_planned_met', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-week_start',),
                'constraints': [models.UniqueConstraint(fields=('owner', 'week_start'), name='unique_weekly_review_per_owner_week')],
            },
        ),
    ]
