# Generated by Django 5.2.16 on 2026-08-19 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_weeklyintention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('unusual', models.CharField(choices=[('usual', 'About usual'), ('less_time', 'Less time than usual'), ('more_time', 'More time than usual')], default='usual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-week_start',),
                'constraints': [models.UniqueConstraint(fields=('owner', 'week_start'), name='unique_planning_session_per_owner_week')],
            },
        ),
    ]
