# Generated by Django 5.2.16 on 2026-08-20 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0039_project_desired_outcome_project_paused_at'),
        ('review', '0003_planningsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('text', models.TextField()),
                ('project_title', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_outcomes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_outcomes', to='lists.project')),
            ],
            options={
                'ordering': ('week_start', 'position', 'id'),
                'indexes': [models.Index(fields=['owner', 'week_start', 'position'], name='outcome_owner_week_idx')],
            },
        ),
    ]
