# Generated by Django 5.2.17 on 2026-09-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_move_content_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
