# Generated by Django 5.2.16 on 2026-07-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_daily_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('system', 'Match my device'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=6),
        ),
    ]
