# Generated by Django 5.2.16 on 2026-08-01 14:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_personal_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_digest_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(default='America/New_York', help_text='Decides when your day starts and ends: what counts as overdue or due today, what the snooze options mean, and when the daily summary arrives.', max_length=64, validators=[accounts.models.validate_time_zone], verbose_name='Time zone'),
        ),
    ]
