# Generated by Django 5.2.16 on 2026-08-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_last_digest_date_user_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compass_purpose',
            field=models.TextField(blank=True, default='', help_text="Why this work matters. Shown on every day's page.", verbose_name='Purpose'),
        ),
        migrations.AddField(
            model_name='user',
            name='compass_question',
            field=models.TextField(blank=True, default='', help_text='The question worth asking each morning.', verbose_name='Guiding question'),
        ),
    ]
