# Generated by Django 5.2.16 on 2026-08-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_compass_purpose_user_compass_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='landing_surface',
            field=models.CharField(choices=[('day', "Today's page"), ('agenda', 'Agenda')], default='day', help_text='Where Clarice opens when you sign in.', max_length=10, verbose_name='Start me on'),
        ),
    ]
