# Generated by Django 5.2.16 on 2026-08-11 02:55

from django.db import migrations, models


# The literal value of accounts.models.GRANDFATHERED_SCOPES at the moment
# this migration was written, not an import of that name -- a migration has
# to keep doing what it did the day it ran even if that constant's value
# changes later. token-scopes-plan.md §3: every token that exists before
# this column does keeps exactly what it can do today (capture + identity),
# not more, so nobody's phone stops working and nobody's token silently
# gains day:read it was never granted.
GRANDFATHERED_SCOPES = "capture:write,identity:read"


def grandfather_existing_tokens(apps, schema_editor):
    PersonalAccessToken = apps.get_model("accounts", "PersonalAccessToken")
    PersonalAccessToken.objects.update(scopes=GRANDFATHERED_SCOPES)


def clear_scopes(apps, schema_editor):
    # The reverse of an UPDATE is not "restore the old NULL" -- there was
    # no scopes column to have a value before this migration existed. This
    # exists so the migration is reversible at all, not to make the
    # reversal meaningful.
    PersonalAccessToken = apps.get_model("accounts", "PersonalAccessToken")
    PersonalAccessToken.objects.update(scopes="")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_landing_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccesstoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalaccesstoken',
            name='scopes',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(grandfather_existing_tokens, clear_scopes),
    ]
