# Generated by Django 5.2.16 on 2026-08-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_deletion_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
