# Generated by Django 5.2.16 on 2026-08-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_email_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='closing_nudge',
            field=models.BooleanField(default=False, help_text='An evening email with what the day held, asking what happened while it is still true. Nothing is sent once you have written the day.', verbose_name='Email me an evening nudge to close the day'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_closing_nudge_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
