"""
Django settings for clarice project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
import sys

from clarice.deployment import is_debug
from clarice.monitoring import initialise as initialise_error_monitoring


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEPLOYMENT_ENVIRONMENT = os.environ.get("DJANGO_ENVIRONMENT", "development")
# "staging" gets everything below this that "production" does -- a
# required SECRET_KEY, secure cookies, HSTS, no debug tracebacks -- since
# the whole point of a staging host is to rehearse production's real
# posture. It differs only in clarice/monitoring.py, which reports
# exclusively for the literal string "production" so staging's own noise
# never buries a real incident. See clarice/deployment.py.
DEBUG = is_debug(DEPLOYMENT_ENVIRONMENT)

# SECURITY WARNING: keep the secret key used in production secret.
if not DEBUG:
    DEBUG = False
    SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
    ALLOWED_HOSTS = [
        os.environ["DJANGO_ALLOWED_HOST"],
        "www." + os.environ["DJANGO_ALLOWED_HOST"],
    ]
    # Managed Postgres cluster, e.g.
    # postgresql://user:password@host:25060/clarice?sslmode=require
    # (see infra/provision-postgres.sh and MIGRATION.md).
    database_url = os.environ["DJANGO_DATABASE_URL"]
    # Only takes effect over real HTTPS; browsers ignore this header over
    # plain HTTP. Start small and only raise it once HTTPS is confirmed
    # working end-to-end, per Django's own warning on this setting.
    SECURE_HSTS_SECONDS = 3600

    # We sit behind an nginx reverse proxy that terminates TLS and talks
    # to us over plain HTTP, so Django needs to trust this header to know
    # a request was actually secure (for CSRF, secure cookies, etc).
    # nginx must set this header itself (see infra/templates/nginx-clarice.conf.j2)
    # or it can be spoofed by any client.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

else:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "insecure-key-for-dev")
    ALLOWED_HOSTS = []


email_delivery = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "smtp" if not DEBUG else "console",
)
if email_delivery == "smtp":
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    # Resend authenticates with the literal username "resend" and an API
    # key as the password; the host is only overridable so that a future
    # provider change doesn't need a code change.
    EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "smtp.resend.com")
    EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ["DJANGO_EMAIL_HOST_USER"]
    EMAIL_HOST_PASSWORD = os.environ["DJANGO_EMAIL_HOST_PASSWORD"]
elif email_delivery == "console":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    raise ImproperlyConfigured(
        "DJANGO_EMAIL_BACKEND must be either 'smtp' or 'console'."
    )

# Sender identity, deliberately outside the branch above. These are what a
# recipient sees, and they must not vary with how a message happened to be
# delivered. DEFAULT_FROM_EMAIL used to be defined as EMAIL_HOST_USER,
# which had two consequences: every password reset was visibly signed by a
# personal Gmail account, and dev and the test suite -- which take the
# console branch -- never exercised the real sender at all, silently
# falling through to Django's webmaster@localhost.
EMAIL_DOMAIN = os.environ.get("DJANGO_EMAIL_DOMAIN", "vinclarice.com")
DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL", f"Clarice <accounts@{EMAIL_DOMAIN}>"
)
# mail_admins() and Django's own error mail send From SERVER_EMAIL, whose
# default is root@localhost. That is not a cosmetic problem now: it is not
# an address on the verified sending domain, so Resend rejects it outright
# and the first production lockout would fail to report itself.
SERVER_EMAIL = os.environ.get(
    "DJANGO_SERVER_EMAIL", f"Clarice notices <notices@{EMAIL_DOMAIN}>"
)
# mail_admins() prefixes every subject with this. Django's default is
# "[Django] ", which labelled Clarice's own notices with the framework they
# were built in -- caught by reading a real one, not by a test.
EMAIL_SUBJECT_PREFIX = "[Clarice] "

# Where the public contact form delivers. A real mailbox rather than a
# send-only address: Resend only sends, so this receives through the IONOS
# mailboxes the domain's MX records point at.
SUPPORT_EMAIL = os.environ.get("DJANGO_SUPPORT_EMAIL", f"support@{EMAIL_DOMAIN}")
# Successful contact-form sends allowed per client IP per hour. nginx
# throttles the same path more bluntly (see infra/templates/
# nginx-clarice.conf.j2); this is the layer with a test.
CONTACT_MAX_PER_HOUR = int(os.environ.get("DJANGO_CONTACT_MAX_PER_HOUR", "5"))

# Production error reporting. The decision itself lives in
# clarice.monitoring so it can be tested; this is only the wiring. Absent a
# DSN nothing is initialised and the SDK is never even imported, which is
# what keeps development and the test suite from reporting anywhere.
ERROR_MONITORING_ENABLED = initialise_error_monitoring(
    dsn=os.environ.get("DJANGO_SENTRY_DSN", ""),
    environment=DEPLOYMENT_ENVIRONMENT,
    # Set by the deploy playbook from the commit being built. "unknown" is
    # honest rather than convenient: an event tagged with a release nobody
    # can find is worse than one that admits it doesn't know.
    release=os.environ.get("DJANGO_RELEASE", "unknown"),
)

# Who gets emailed about pending signups and account lockouts
# (see accounts.emails and accounts.apps.AccountsConfig.ready). This is an
# internal routing decision and never appears in a header a user reads.
ADMINS = [("Vince", os.environ.get("DJANGO_ADMIN_EMAIL", "vincentjg01@gmail.com"))]


# Application definition

INSTALLED_APPS = [
    # Must come before django.contrib.admin: it overrides the built-in
    # admin's templates to render the themed UI (see UNFOLD below).
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "axes",
    "accounts",
    "lists",
    "capture",
    # The daily domain -- Daily Entry now, Daily Focus and the Personal
    # Compass as Crane 1 continues. Its own app rather than more tables in
    # `lists`, because a day is not a task and the vision document's whole
    # argument is that the Daily Page is a lens over durable records rather
    # than another place to keep them.
    "daily",
    # Routines are a peer of tasks and of days, not a part of either. Its
    # own app because that boundary is the load-bearing one in crane-plan.md
    # §3, and an app is the cheapest way to stop a routine quietly becoming
    # a kind of Item later.
    "routines",
    # The weekly review: a read layer over lists, daily, routines and
    # capture, plus one small record of its own. Its own app because
    # architecture-trajectory.md §4 anticipates exactly one
    # review-and-analytics module reading every occurrence table, and
    # because a week is not a kind of day -- see crane-plan.md §8.
    "review",
]


def environment_callback(request):
    """Small colored label shown in the admin header (see UNFOLD["ENVIRONMENT"]
    below) so it's obvious at a glance which server you're looking at.

    Staging and production both deploy with DJANGO_ENVIRONMENT=production
    (see infra/deploy-playbook.yaml), so DEBUG alone can't tell them apart --
    the domain each was deployed with (DJANGO_ALLOWED_HOST) is the only
    reliable signal.
    """
    if DEBUG:
        return ["Development", "info"]
    if os.environ.get("DJANGO_ALLOWED_HOST", "").startswith("staging."):
        return ["Staging", "warning"]
    return ["Production", "danger"]


UNFOLD = {
    "SITE_TITLE": "Clarice admin",
    "SITE_HEADER": "Clarice",
    "SITE_SYMBOL": "checklist",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "clarice.settings.environment_callback",
}

AUTH_USER_MODEL = "accounts.User"
AUTHENTICATION_BACKENDS = [
    # Must come first: checks/records lockouts before delegating to
    # ModelBackend for the actual credential check.
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
]
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

MIDDLEWARE = [
    # First, so the nonce exists on the request before anything can
    # render a template that needs it.
    'clarice.middleware.ContentSecurityPolicyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Straight after authentication, since it needs request.user: it
    # activates that user's own time zone so every day-boundary decision
    # below (and in every view) is made against their day, not the
    # server's.
    'accounts.middleware.TimeZoneMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Must be last: axes needs to see the response/exception from
    # everything above it to track failed logins.
    'axes.middleware.AxesMiddleware',
]

# Lock out an account after 5 failed attempts for an hour, tracked by
# username alone (not paired with IP) so a distributed/rotating-IP attempt
# against one account still gets caught -- nginx's rate limiting (see
# infra/templates/nginx-clarice.conf.j2) is what handles the by-IP case.
# See accounts.apps.AccountsConfig.ready for the lockout notification email.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hour
AXES_LOCKOUT_PARAMETERS = ["username"]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = "accounts/lockout.html"

# axes.W006 warns that username-only lockout can be bypassed by rotating
# IP/cookies -- true, but nginx's by-IP rate limiting already covers that
# case (see infra/templates/nginx-clarice.conf.j2), and username-only
# is a deliberate choice here so a single attacker can't dodge lockout by
# rotating IPs either.
SILENCED_SYSTEM_CHECKS = ["axes.W006"]

ROOT_URLCONF = 'clarice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clarice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:
    # Local dev runs on Postgres now, not SQLite: Item.Meta's
    # unique_active_item uses nulls_distinct=False -- "Postgres 15+ only"
    # per its own comment -- so a SQLite run silently omits the constraint
    # production enforces, and the local suite passed while proving
    # something weaker than it appeared to
    # (design/architecture-trajectory.md §3). `docker compose up -d db`
    # starts the local cluster this default points at; DJANGO_DATABASE_URL
    # still overrides it, which is exactly what CI does to reach its own
    # service container instead (.github/workflows/ci.yml).
    database_url = os.environ.get(
        "DJANGO_DATABASE_URL",
        "postgresql://clarice:clarice@localhost:5433/clarice",
    )
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': dj_database_url.parse(
            database_url,
            conn_max_age=600,
            ssl_require=True,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# `manage.py test` runs hundreds of logins against real accounts, and the
# production hasher (PBKDF2, deliberately slow) turns that into multiple
# seconds per login-based test for no real coverage benefit -- nothing
# about hasher performance is under test. MD5 here only ever touches the
# throwaway per-run test database, never production data.
if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
VITE_DEV_SERVER_URL = os.environ.get("VITE_DEV_SERVER_URL", "")

if DEPLOYMENT_ENVIRONMENT == "production":
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": (
                "whitenoise.storage.CompressedManifestStaticFilesStorage"
            ),
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "root": {"handlers": ["console"], "level": "INFO"},
    },
}
