"""
Django settings for clarice project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
import sys

from clarice.deployment import is_debug, test_database_name
from clarice.monitoring import initialise as initialise_error_monitoring


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEPLOYMENT_ENVIRONMENT = os.environ.get("DJANGO_ENVIRONMENT", "development")
# "staging" gets everything below this that "production" does -- a
# required SECRET_KEY, secure cookies, HSTS, no debug tracebacks -- since
# the whole point of a staging host is to rehearse production's real
# posture. It differs only in clarice/monitoring.py, which reports
# exclusively for the literal string "production" so staging's own noise
# never buries a real incident. See clarice/deployment.py.
DEBUG = is_debug(DEPLOYMENT_ENVIRONMENT)

# SECURITY WARNING: keep the secret key used in production secret.
if not DEBUG:
    DEBUG = False
    SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
    ALLOWED_HOSTS = [
        os.environ["DJANGO_ALLOWED_HOST"],
        "www." + os.environ["DJANGO_ALLOWED_HOST"],
    ]
    # Managed Postgres cluster, e.g.
    # postgresql://user:password@host:25060/clarice?sslmode=require
    # (see infra/provision-postgres.sh and MIGRATION.md).
    database_url = os.environ["DJANGO_DATABASE_URL"]
    # Only takes effect over real HTTPS; browsers ignore this header over
    # plain HTTP.
    #
    # ~~Start small and only raise it once HTTPS is confirmed working
    # end-to-end, per Django's own warning on this setting.~~ Raised from one
    # hour to a year on August 26, 2026 -- security-and-resilience-plan.md 1.6.
    # HTTPS has been confirmed end to end for weeks: certbot renews
    # automatically and the playbook exercises it. At one hour the header was
    # close to decorative, since somebody returning the next day had no
    # protection against a downgrade at all, which is the attack it is for.
    #
    # The plan names the habit rather than this instance, and the habit is
    # worth more: a conservative default with a condition attached needs
    # somebody holding the condition, or it becomes permanent by inattention.
    # Two turned up the same week -- this and the CSP's report-only mode. Both
    # are now held by an assertion rather than by memory.
    SECURE_HSTS_SECONDS = 31536000
    # Nothing is served from a subdomain today, which is exactly when this is
    # cheap to turn on: it forbids a future `staging.` or `api.` from being
    # reachable over plain HTTP before anybody builds one.
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # `SECURE_HSTS_PRELOAD` is deliberately not here. Browsers ship the preload
    # list, so withdrawal takes months rather than a deploy -- a genuinely
    # hard-to-reverse choice, which by principles.md is one to make on evidence
    # rather than on the way past. It is that plan's D4.

    # We sit behind an nginx reverse proxy that terminates TLS and talks
    # to us over plain HTTP, so Django needs to trust this header to know
    # a request was actually secure (for CSRF, secure cookies, etc).
    # nginx must set this header itself (see infra/templates/nginx-clarice.conf.j2)
    # or it can be spoofed by any client.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

else:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "insecure-key-for-dev")
    ALLOWED_HOSTS = []


email_delivery = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    # `resend` rather than `smtp` since August 18, 2026: DigitalOcean drops
    # outbound 25, 465 and 587 on every Droplet, so SMTP cannot leave the host
    # this deploys to. See design/mail-transport-plan.md for the measurement.
    # The SMTP arm is kept rather than deleted -- it is deselected, so reverting
    # is a variable and a redeploy, and the day those ports open nothing has to
    # be rewritten to use them.
    "resend" if not DEBUG else "console",
)
if email_delivery == "resend":
    # PROCESSOR: Resend. Holds delivery records for every message this
    # application sends -- recipient address, subject, and when it went. Those
    # survive `accounts.services.purge_account`, which erases this database and
    # nothing outside it. Clearing them is manual and permanently so, decided
    # August 26, 2026 as `security-and-resilience-plan.md` D1: automating it
    # means a delete-capable credential living on the droplet for the rest of
    # the application's life, to save a step taken a handful of times a year.
    EMAIL_BACKEND = "clarice.mail.ResendBackend"
    # Required *and* non-empty, which os.environ[...] alone does not give:
    # the playbook templates this variable to '' on the other arms, so a
    # misconfiguration reaches the container as present-and-blank rather than
    # absent. Left at a bare lookup, that boots cleanly and fails on the first
    # password reset -- which is the whole failure mode being fixed here.
    RESEND_API_KEY = os.environ.get("DJANGO_RESEND_API_KEY", "")
    if not RESEND_API_KEY:
        raise ImproperlyConfigured(
            "DJANGO_RESEND_API_KEY is required when DJANGO_EMAIL_BACKEND is "
            "'resend'."
        )
elif email_delivery == "smtp":
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    # Resend authenticates with the literal username "resend" and an API
    # key as the password; the host is only overridable so that a future
    # provider change doesn't need a code change.
    EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "smtp.resend.com")
    EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ["DJANGO_EMAIL_HOST_USER"]
    EMAIL_HOST_PASSWORD = os.environ["DJANGO_EMAIL_HOST_PASSWORD"]
elif email_delivery == "console":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    raise ImproperlyConfigured(
        "DJANGO_EMAIL_BACKEND must be 'resend', 'smtp' or 'console'."
    )

# Sender identity, deliberately outside the branch above. These are what a
# recipient sees, and they must not vary with how a message happened to be
# delivered. DEFAULT_FROM_EMAIL used to be defined as EMAIL_HOST_USER,
# which had two consequences: every password reset was visibly signed by a
# personal Gmail account, and dev and the test suite -- which take the
# console branch -- never exercised the real sender at all, silently
# falling through to Django's webmaster@localhost.
EMAIL_DOMAIN = os.environ.get("DJANGO_EMAIL_DOMAIN", "vinclarice.com")

# **Django asks the network for this host's name every time a message is built,
# and on a machine where reverse DNS is slow that blocks the request.**
# `EmailMessage.message()` stamps a `Message-ID` using
# `django.core.mail.utils.DNS_NAME`, which calls `socket.getfqdn()` once per
# process and caches the answer. On this laptop that call takes **12 seconds**,
# measured -- which is how it was found: `test_leaving`'s schedule-deletion
# journey began failing, and the cause was neither the code under test nor the
# MFA work that landed beside it. Playwright waits ten seconds; the send took
# twelve.
#
# Pre-seeding the cache is the whole fix. `message.py` binds `DNS_NAME` by
# value at import, so replacing the module attribute would not take -- what
# works is filling the cache on the instance everything already holds.
#
# **Production never paid this**, and the fix is not for its benefit:
# `clarice.mail.ResendBackend` builds Resend's JSON payload from the message's
# own fields and never calls `.message()`. What does call it is the locmem
# backend the test suite runs on -- deliberately, "to trigger header
# validation" -- and the console backend used in development.
#
# The name is better than the one it replaces either way. A `Message-ID`
# claiming to come from `Vincez` says nothing true about where the mail is
# from; this one names the domain the mail actually claims to be from.
from django.core.mail.utils import DNS_NAME as _dns_name  # noqa: E402

_dns_name._fqdn = os.environ.get("DJANGO_MAIL_FQDN", EMAIL_DOMAIN)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL", f"Clarice <accounts@{EMAIL_DOMAIN}>"
)
# mail_admins() and Django's own error mail send From SERVER_EMAIL, whose
# default is root@localhost. That is not a cosmetic problem now: it is not
# an address on the verified sending domain, so Resend rejects it outright
# and the first production lockout would fail to report itself.
SERVER_EMAIL = os.environ.get(
    "DJANGO_SERVER_EMAIL", f"Clarice notices <notices@{EMAIL_DOMAIN}>"
)
# mail_admins() prefixes every subject with this. Django's default is
# "[Django] ", which labelled Clarice's own notices with the framework they
# were built in -- caught by reading a real one, not by a test.
# A send that never returns is a transaction that never closes.
# accounts.services.request_deletion sends *inside* its atomic block --
# deliberately, so the scheduled-for-deletion timestamp cannot outlive the
# warning that makes the grace period a real protection -- which puts an SMTP
# round trip between BEGIN and COMMIT. Unset, smtplib inherits the global
# default socket timeout, which is also unset, so a hung relay would hold that
# transaction open with no bound at all, on one worker with four threads.
#
# Ten seconds: far longer than Resend's API needs and far shorter than a
# person will wait on a form that is already doing something irreversible.
EMAIL_TIMEOUT = 10

EMAIL_SUBJECT_PREFIX = "[Clarice] "

# Where the public contact form delivers. A real mailbox rather than a
# send-only address: Resend only sends, so this receives through the IONOS
# mailboxes the domain's MX records point at.
SUPPORT_EMAIL = os.environ.get("DJANGO_SUPPORT_EMAIL", f"support@{EMAIL_DOMAIN}")

# Where this site actually is, for the one email that has no request to build a
# URL from. Every other absolute link in an email comes from
# `request.build_absolute_uri`; the account-approved message is sent from a
# post_save signal fired by an admin ticking a box, and a signal has no request.
#
# Derived from EMAIL_DOMAIN rather than declared separately, so the address mail
# comes *from* and the address it points *at* cannot disagree without somebody
# deliberately overriding this.
SITE_URL = os.environ.get("DJANGO_SITE_URL", f"https://{EMAIL_DOMAIN}")
# Successful contact-form sends allowed per client IP, per *worker lifetime*
# rather than per hour despite the name -- CONTACT_WINDOW_SECONDS sets an hour
# on the key, but the default cache is LocMemCache and one gunicorn worker
# recycles every ~500 requests, which ordinary static-file traffic reaches on
# its own. nginx-clarice.conf.j2 carries the full reasoning; the name is left
# alone because renaming a setting to describe a deployment accident would
# make the code wrong if the cache ever became shared.
#
# nginx throttles the same path more bluntly and is the bound that holds; this
# is the layer with a test.
CONTACT_MAX_PER_HOUR = int(os.environ.get("DJANGO_CONTACT_MAX_PER_HOUR", "5"))

# Production error reporting. The decision itself lives in
# clarice.monitoring so it can be tested; this is only the wiring. Absent a
# DSN nothing is initialised and the SDK is never even imported, which is
# what keeps development and the test suite from reporting anywhere.
#
# PROCESSOR: Sentry. Holds error reports, which carry a user id and whatever
# request context survived clarice.monitoring's exclusions -- note text is
# scrubbed there, deliberately, and that is a narrowing rather than an
# absence. Reports already sent survive `accounts.services.purge_account`.
# Clearing them is manual and permanently so; see the Resend marker above for
# the reasoning, which is the same reasoning and one decision.
ERROR_MONITORING_ENABLED = initialise_error_monitoring(
    dsn=os.environ.get("DJANGO_SENTRY_DSN", ""),
    environment=DEPLOYMENT_ENVIRONMENT,
    # Set by the deploy playbook from the commit being built. "unknown" is
    # honest rather than convenient: an event tagged with a release nobody
    # can find is worse than one that admits it doesn't know.
    release=os.environ.get("DJANGO_RELEASE", "unknown"),
)

# Who gets emailed about pending signups and account lockouts
# (see accounts.emails and accounts.apps.AccountsConfig.ready). This is an
# internal routing decision and never appears in a header a user reads.
ADMINS = [("Vince", os.environ.get("DJANGO_ADMIN_EMAIL", "vincentjg01@gmail.com"))]


# Application definition

INSTALLED_APPS = [
    # Must come before django.contrib.admin: it overrides the built-in
    # admin's templates to render the themed UI (see UNFOLD below).
    #
    # `BasicAppConfig` rather than the default one, since August 23, 2026:
    # unfold's `DefaultAppConfig.ready()` assigns `admin.site` outright, which
    # silently discarded the second-factor site `default_site` had just built.
    # `BasicAppConfig` is unfold's own hook for a project that supplies its own
    # site -- same app, no swap. See `clarice/admin.py`.
    "unfold.apps.BasicAppConfig",
    # Not "django.contrib.admin": `clarice.admin.VerifiedAdminConfig` is the
    # same app with `default_site` pointed at the second-factor gate. See
    # that module for why this is the hook rather than assigning
    # `admin.site.__class__`, which django-otp's README suggests and which
    # breaks the lazy proxy.
    "clarice.admin.VerifiedAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "axes",
    # A second factor for the accounts that can read everything --
    # design/admin-mfa-plan.md, increment 1. Installed here and enforced
    # nowhere yet: this increment only makes `request.user.is_verified()`
    # answerable, so that increment 4 has something to gate on and can be
    # deployed after somebody has actually enrolled.
    #
    # `otp_static` is the recovery codes, and it is not optional-in-practice:
    # a second factor with no way back in is a way to lose the admin account
    # rather than a way to protect it.
    #
    # **Their app labels are deliberately outside `accounts.export.OWNED_APPS`.**
    # That module walks whole apps, so adding these there would sweep
    # `TOTPDevice.key` -- the shared secret -- and the static tokens into the
    # archive a person downloads. `test_mfa.py` holds that boundary; the
    # exclusion is a decision, not the accident of app naming it resembles.
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    "accounts",
    "lists",
    # `capture` stood here until August 15, 2026. It held the Inbox -- `Capture`
    # and `Idea` -- which Heron 4b deleted; the app itself stayed one more
    # deploy, holding nothing but migrations, because Django needs an app
    # installed for its migrations to run and `0008_delete_idea_capture` is what
    # actually dropped the tables. That migration is applied in production, so
    # the app is gone too.
    #
    # `django_migrations` keeps eight rows for it. They are inert -- Django
    # ignores rows for apps it does not know -- and deleting them by hand would
    # be a write against production's bookkeeping to tidy something nothing
    # reads.
    #
    # The knowledge core, moved in from its own repository on August 14, 2026.
    # Second Mind's design still governs it -- see that project's docs/ -- and
    # the code lives here because this is the repository with the deployment,
    # the users, the CI and the surviving accounts.User. Those two directions
    # pointing opposite ways is deliberate, not a reversal.
    #
    # It replaced `capture` rather than sitting beside it. The three sentences
    # that stood here described a crossover in progress -- both apps installed,
    # two `/api/v1/capture` definitions colliding, neither moved yet -- and all
    # three stopped being true on August 15 when Heron finished. There is one
    # capture surface at `/mind/`, one endpoint at `/api/v1/capture` served by
    # `mind/api_v1.py`, and `capture` is gone.
    "mind",
    # The daily domain -- Daily Entry now, Daily Focus and the Personal
    # Compass as Crane 1 continues. Its own app rather than more tables in
    # `lists`, because a day is not a task and the vision document's whole
    # argument is that the Daily Page is a lens over durable records rather
    # than another place to keep them.
    "daily",
    # Routines are a peer of tasks and of days, not a part of either. Its
    # own app because that boundary is the load-bearing one in crane-plan.md
    # §3, and an app is the cheapest way to stop a routine quietly becoming
    # a kind of Item later.
    "routines",
    # The weekly review: a read layer over lists, daily, routines and
    # capture, plus one small record of its own. Its own app because
    # architecture-trajectory.md §4 anticipates exactly one
    # review-and-analytics module reading every occurrence table, and
    # because a week is not a kind of day -- see crane-plan.md §8.
    "review",
]


def environment_callback(request):
    """Small colored label shown in the admin header (see UNFOLD["ENVIRONMENT"]
    below) so it's obvious at a glance which server you're looking at.

    Staging and production both deploy with DJANGO_ENVIRONMENT=production
    (see infra/deploy-playbook.yaml), so DEBUG alone can't tell them apart --
    the domain each was deployed with (DJANGO_ALLOWED_HOST) is the only
    reliable signal.
    """
    if DEBUG:
        return ["Development", "info"]
    if os.environ.get("DJANGO_ALLOWED_HOST", "").startswith("staging."):
        return ["Staging", "warning"]
    return ["Production", "danger"]


UNFOLD = {
    "SITE_TITLE": "Clarice admin",
    "SITE_HEADER": "Clarice",
    "SITE_SYMBOL": "checklist",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "clarice.settings.environment_callback",
}

AUTH_USER_MODEL = "accounts.User"
AUTHENTICATION_BACKENDS = [
    # Must come first: checks/records lockouts before delegating to
    # ModelBackend for the actual credential check.
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
]
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

MIDDLEWARE = [
    # First, so the nonce exists on the request before anything can
    # render a template that needs it.
    'clarice.middleware.ContentSecurityPolicyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Directly after authentication, because it wraps the `request.user` that
    # middleware set: it attaches `is_verified()`, which answers "has this
    # session presented a second factor", as opposed to `is_authenticated`,
    # which answers "did it present a password". Nothing consults it yet --
    # design/admin-mfa-plan.md increment 4 is what gates on it.
    #
    # Before TimeZoneMiddleware rather than after, only because that one reads
    # `request.user` and should read the same object every other layer sees.
    'django_otp.middleware.OTPMiddleware',
    # Straight after authentication, since it needs request.user: it
    # activates that user's own time zone so every day-boundary decision
    # below (and in every view) is made against their day, not the
    # server's.
    'accounts.middleware.TimeZoneMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Must be last: axes needs to see the response/exception from
    # everything above it to track failed logins.
    'axes.middleware.AxesMiddleware',
]

# Lock out an account after 5 failed attempts for an hour, tracked by
# username alone (not paired with IP) so a distributed/rotating-IP attempt
# against one account still gets caught -- nginx's rate limiting (see
# infra/templates/nginx-clarice.conf.j2) is what handles the by-IP case.
# See accounts.apps.AccountsConfig.ready for the lockout notification email.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hour
AXES_LOCKOUT_PARAMETERS = ["username"]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = "accounts/lockout.html"

# axes.W006 warns that username-only lockout can be bypassed by rotating
# IP/cookies -- true, but nginx's by-IP rate limiting already covers that
# case (see infra/templates/nginx-clarice.conf.j2), and username-only
# is a deliberate choice here so a single attacker can't dodge lockout by
# rotating IPs either.
SILENCED_SYSTEM_CHECKS = ["axes.W006"]

ROOT_URLCONF = 'clarice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clarice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:
    # Local dev runs on Postgres now, not SQLite: Item.Meta's
    # unique_active_item uses nulls_distinct=False -- "Postgres 15+ only"
    # per its own comment -- so a SQLite run silently omits the constraint
    # production enforces, and the local suite passed while proving
    # something weaker than it appeared to
    # (design/architecture-trajectory.md §3). `docker compose up -d db`
    # starts the local cluster this default points at; DJANGO_DATABASE_URL
    # still overrides it, which is exactly what CI does to reach its own
    # service container instead (.github/workflows/ci.yml).
    database_url = os.environ.get(
        "DJANGO_DATABASE_URL",
        "postgresql://clarice:clarice@localhost:5433/clarice",
    )
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': dj_database_url.parse(
            database_url,
            conn_max_age=600,
            ssl_require=True,
        )
    }

# **Two `manage.py test` runs in this repository destroy each other's database.**
# Django derives the test database's name from the one above, so every run in
# this checkout is called `test_clarice` -- and the second one to start finds it
# already there, asks whether to delete it, and gets `EOFError` because nothing
# is attached to stdin. Worse when the timing is unluckier: the first run's
# teardown drops the database the second is still using, and the failure arrives
# as a hundred `setUpClass` errors that look like a broken migration and read
# nothing like contention. Both were observed on August 19, 2026, with two
# sessions working in this tree at once.
#
# **The default now carries the checkout**, rather than an opt-in that only
# helped whoever remembered it -- which was never going to be the sessions that
# collide. `clarice.deployment.test_database_name` owns the reasoning and the
# two properties that make a derived name safe: stable per checkout, so a
# laptop keeps one test database rather than an orphan per run, and different
# between checkouts, which is what a worktree is.
#
# `DJANGO_TEST_DB_SUFFIX` still works and still wins. It covers the one case a
# path cannot see: two runs inside a single checkout, such as `manage.py test`
# and `pytest` at once.
#
#     DJANGO_TEST_DB_SUFFIX=b .venv/Scripts/python.exe src/manage.py test ...
#
# Note this is not `--parallel`, which clones from the database named here and
# therefore collides in exactly the same place.
DATABASES["default"].setdefault("TEST", {})
DATABASES["default"]["TEST"]["NAME"] = test_database_name(
    database_name=DATABASES["default"]["NAME"],
    base_dir=BASE_DIR,
    override=os.environ.get("DJANGO_TEST_DB_SUFFIX"),
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# `manage.py test` runs hundreds of logins against real accounts, and the
# production hasher (PBKDF2, deliberately slow) turns that into multiple
# seconds per login-based test for no real coverage benefit -- nothing
# about hasher performance is under test. MD5 here only ever touches the
# throwaway per-run test database, never production data.
if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
VITE_DEV_SERVER_URL = os.environ.get("VITE_DEV_SERVER_URL", "")

if DEPLOYMENT_ENVIRONMENT == "production":
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": (
                "whitenoise.storage.CompressedManifestStaticFilesStorage"
            ),
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "root": {"handlers": ["console"], "level": "INFO"},
    },
}
