"""
Django settings for clarice project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEPLOYMENT_ENVIRONMENT = os.environ.get("DJANGO_ENVIRONMENT", "development")
DEBUG = DEPLOYMENT_ENVIRONMENT != "production"

# SECURITY WARNING: keep the secret key used in production secret.
if not DEBUG:
    DEBUG = False
    SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
    ALLOWED_HOSTS = [
        os.environ["DJANGO_ALLOWED_HOST"],
        "www." + os.environ["DJANGO_ALLOWED_HOST"],
    ]
    db_path = os.environ["DJANGO_DB_PATH"]
    # Only takes effect over real HTTPS; browsers ignore this header over
    # plain HTTP. Start small and only raise it once HTTPS is confirmed
    # working end-to-end, per Django's own warning on this setting.
    SECURE_HSTS_SECONDS = 3600

    # We sit behind an nginx reverse proxy that terminates TLS and talks
    # to us over plain HTTP, so Django needs to trust this header to know
    # a request was actually secure (for CSRF, secure cookies, etc).
    # nginx must set this header itself (see infra/templates/nginx-clarice.conf.j2)
    # or it can be spoofed by any client.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

else:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "insecure-key-for-dev")
    ALLOWED_HOSTS = []
    db_path = os.environ.get("DJANGO_DB_PATH", BASE_DIR / "db.sqlite3")


email_delivery = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "smtp" if not DEBUG else "console",
)
if email_delivery == "smtp":
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ["DJANGO_EMAIL_HOST_USER"]
    EMAIL_HOST_PASSWORD = os.environ["DJANGO_EMAIL_HOST_PASSWORD"]
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
elif email_delivery == "console":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    raise ImproperlyConfigured(
        "DJANGO_EMAIL_BACKEND must be either 'smtp' or 'console'."
    )

# Who gets emailed about pending signups and account lockouts
# (see accounts.emails and accounts.apps.AccountsConfig.ready).
ADMINS = [("Vince", os.environ.get("DJANGO_ADMIN_EMAIL", "vincentjg01@gmail.com"))]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "axes",
    "accounts",
    "lists",
]

if DEPLOYMENT_ENVIRONMENT != "production":
    INSTALLED_APPS.append("functional_tests")

AUTH_USER_MODEL = "accounts.User"
AUTHENTICATION_BACKENDS = [
    # Must come first: checks/records lockouts before delegating to
    # ModelBackend for the actual credential check.
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
]
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Must be last: axes needs to see the response/exception from
    # everything above it to track failed logins.
    'axes.middleware.AxesMiddleware',
]

# Lock out an account after 5 failed attempts for an hour, tracked by
# username alone (not paired with IP) so a distributed/rotating-IP attempt
# against one account still gets caught -- nginx's rate limiting (see
# infra/templates/nginx-clarice.conf.j2) is what handles the by-IP case.
# See accounts.apps.AccountsConfig.ready for the lockout notification email.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hour
AXES_LOCKOUT_PARAMETERS = ["username"]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = "accounts/lockout.html"

# axes.W006 warns that username-only lockout can be bypassed by rotating
# IP/cookies -- true, but nginx's by-IP rate limiting already covers that
# case (see infra/templates/nginx-clarice.conf.j2), and username-only
# is a deliberate choice here so a single attacker can't dodge lockout by
# rotating IPs either.
SILENCED_SYSTEM_CHECKS = ["axes.W006"]

ROOT_URLCONF = 'clarice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clarice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': db_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# `manage.py test` runs hundreds of logins against real accounts, and the
# production hasher (PBKDF2, deliberately slow) turns that into multiple
# seconds per login-based test for no real coverage benefit -- nothing
# about hasher performance is under test. MD5 here only ever touches the
# throwaway per-run test database, never production data.
if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
VITE_DEV_SERVER_URL = os.environ.get("VITE_DEV_SERVER_URL", "")

if DEPLOYMENT_ENVIRONMENT == "production":
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": (
                "whitenoise.storage.CompressedManifestStaticFilesStorage"
            ),
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "root": {"handlers": ["console"], "level": "INFO"},
    },
}
