# Generated by Django 6.1 on 2026-08-12 22:50

import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.TextField()),
                ('concept_type', models.CharField(choices=[('person', 'Person'), ('place', 'Place'), ('object', 'Object'), ('project', 'Project'), ('activity', 'Activity'), ('motif', 'Motif')], max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='mind.conceptcandidate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionHypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('detector', models.CharField(max_length=48)),
                ('relation', models.CharField(blank=True, choices=[('relates_to', 'Relates To'), ('answers', 'Answers'), ('member_of', 'Member Of'), ('contradicts', 'Contradicts'), ('supersedes', 'Supersedes'), ('developed_from', 'Developed From')], max_length=20, null=True)),
                ('confidence', models.FloatField()),
                ('label', models.TextField()),
                ('claim_text', models.TextField(blank=True, null=True)),
                ('index_version', models.CharField(max_length=32)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_surfaced_at', models.DateTimeField(blank=True, null=True)),
                ('surface_count', models.PositiveIntegerField(default=0)),
                ('review_window_expires_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('dismissed', 'Dismissed'), ('expired', 'Expired'), ('renamed', 'Renamed')], max_length=16, null=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypotheses', to='mind.conceptcandidate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'connection hypotheses',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_content', models.TextField(blank=True, default='')),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('share', 'Share'), ('import', 'Import'), ('api', 'Api')], max_length=16)),
                ('import_key', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('search_original', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('original_content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_start', models.PositiveIntegerField(blank=True, null=True)),
                ('span_end', models.PositiveIntegerField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('explicit', 'Explicit'), ('inferred', 'Inferred')], max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('index_version', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='mind.conceptcandidate')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='mind.node')),
            ],
        ),
        migrations.CreateModel(
            name='HypothesisMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_start', models.PositiveIntegerField(blank=True, null=True)),
                ('span_end', models.PositiveIntegerField(blank=True, null=True)),
                ('contribution_reason', models.TextField(blank=True, null=True)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='mind.connectionhypothesis')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypothesis_memberships', to='mind.node')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('relates_to', 'Relates To'), ('answers', 'Answers'), ('member_of', 'Member Of'), ('contradicts', 'Contradicts'), ('supersedes', 'Supersedes'), ('developed_from', 'Developed From')], max_length=20)),
                ('origin', models.CharField(choices=[('explicit', 'Explicit'), ('inferred', 'Inferred')], max_length=16)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to=settings.AUTH_USER_MODEL)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='mind.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='mind.node')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(max_length=32)),
                ('mime_type', models.CharField(max_length=127)),
                ('byte_size', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=128)),
                ('storage_key', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mind.node')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('captured', 'Captured'), ('revised', 'Revised'), ('concept_extracted', 'Concept Extracted'), ('concept_confirmed', 'Concept Confirmed'), ('alias_confirmed', 'Alias Confirmed'), ('mention_proposed', 'Mention Proposed'), ('mention_confirmed', 'Mention Confirmed'), ('edge_created', 'Edge Created'), ('edge_removed', 'Edge Removed'), ('hypothesis_proposed', 'Hypothesis Proposed'), ('hypothesis_surfaced', 'Hypothesis Surfaced'), ('hypothesis_resolved', 'Hypothesis Resolved'), ('thread_articulated', 'Thread Articulated'), ('reviewed', 'Reviewed'), ('imported', 'Imported'), ('archived', 'Archived'), ('deleted', 'Deleted')], max_length=32)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('actor', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='mind.node')),
            ],
        ),
        migrations.CreateModel(
            name='RetrievalMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('context', models.CharField(choices=[('search', 'Search'), ('capture', 'Capture')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misses', to=settings.AUTH_USER_MODEL)),
                ('resolved_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mind.node')),
            ],
            options={
                'verbose_name_plural': 'retrieval misses',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=64)),
                ('search_body', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('body', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='mind.node')),
            ],
        ),
        migrations.AddIndex(
            model_name='conceptcandidate',
            index=models.Index(condition=models.Q(('merged_into__isnull', True), ('retired_at__isnull', True)), fields=['owner', 'concept_type'], name='concept_canonical'),
        ),
        migrations.AddConstraint(
            model_name='conceptcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into', models.F('id')), _negated=True), name='concept_no_self_merge'),
        ),
        migrations.AddConstraint(
            model_name='conceptcandidate',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('label'), models.F('concept_type'), condition=models.Q(('retired_at__isnull', True)), name='concept_label_unique'),
        ),
        migrations.AddIndex(
            model_name='connectionhypothesis',
            index=models.Index(condition=models.Q(('resolved_at__isnull', True)), fields=['owner', '-confidence'], name='hypothesis_open'),
        ),
        migrations.AddIndex(
            model_name='connectionhypothesis',
            index=models.Index(fields=['owner', 'detector', 'resolution'], name='hypothesis_by_detector'),
        ),
        migrations.AddConstraint(
            model_name='connectionhypothesis',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='hypothesis_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='connectionhypothesis',
            constraint=models.UniqueConstraint(fields=('owner', 'fingerprint'), name='hypothesis_fingerprint_unique'),
        ),
        migrations.AddConstraint(
            model_name='connectionhypothesis',
            constraint=models.CheckConstraint(condition=models.Q(('review_window_expires_at__isnull', True), ('first_surfaced_at__isnull', False), _connector='OR'), name='hypothesis_window_requires_surfacing'),
        ),
        migrations.AddConstraint(
            model_name='connectionhypothesis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('first_surfaced_at__isnull', True), ('surface_count', 0)), models.Q(('first_surfaced_at__isnull', False), ('surface_count__gt', 0)), _connector='OR'), name='hypothesis_surface_count_agrees'),
        ),
        migrations.AddConstraint(
            model_name='connectionhypothesis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution__isnull', True), ('resolved_at__isnull', True)), models.Q(('resolution__isnull', False), ('resolved_at__isnull', False)), _connector='OR'), name='hypothesis_resolution_paired'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(condition=models.Q(('archived_at__isnull', True), ('deleted_at__isnull', True)), fields=['owner', '-captured_at'], name='node_live_captured_at'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['search_original'], name='node_search_original'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.CheckConstraint(condition=models.Q(('import_key__isnull', True), ('source', 'import'), _connector='OR'), name='node_import_key_requires_import_source'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(condition=models.Q(('import_key__isnull', False)), fields=('owner', 'import_key'), name='node_import_key_unique'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['concept', 'node'], name='mention_by_concept'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(condition=models.Q(('confirmed_at__isnull', False)), fields=['concept'], name='mention_confirmed'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('span_end__isnull', True), ('span_start__isnull', True)), models.Q(('span_end__isnull', False), ('span_start__isnull', False)), _connector='OR'), name='mention_span_paired'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.CheckConstraint(condition=models.Q(('span_start__isnull', True), ('span_end__gt', models.F('span_start')), _connector='OR'), name='mention_span_ordered'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(fields=('node', 'concept', 'span_start', 'span_end'), name='mention_unique', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='hypothesismember',
            index=models.Index(fields=['node'], name='hypothesis_member_by_node'),
        ),
        migrations.AddConstraint(
            model_name='hypothesismember',
            constraint=models.UniqueConstraint(fields=('hypothesis', 'node'), name='hypothesis_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='hypothesismember',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('span_end__isnull', True), ('span_start__isnull', True)), models.Q(('span_end__isnull', False), ('span_start__isnull', False)), _connector='OR'), name='hypothesis_member_span_paired'),
        ),
        migrations.AddConstraint(
            model_name='hypothesismember',
            constraint=models.CheckConstraint(condition=models.Q(('span_start__isnull', True), ('span_end__gt', models.F('span_start')), _connector='OR'), name='hypothesis_member_span_ordered'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['from_node', 'relation'], name='edge_from'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['to_node', 'relation'], name='edge_to'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('from_node', models.F('to_node')), _negated=True), name='edge_no_self_link'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='edge_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('from_node', 'to_node', 'relation'), name='edge_directed_unique'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('from_node', 'to_node'), django.db.models.functions.comparison.Greatest('from_node', 'to_node'), condition=models.Q(('relation', 'relates_to')), name='edge_symmetric_unique'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gte', 0)), name='attachment_size_non_negative'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['owner', '-occurred_at'], name='event_timeline'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['node', 'event_type', 'occurred_at'], name='event_by_node'),
        ),
        migrations.AddIndex(
            model_name='retrievalmiss',
            index=models.Index(fields=['owner', '-created_at'], name='miss_recent'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['node', '-seq'], name='revision_latest'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['search_body'], name='revision_search_body'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.CheckConstraint(condition=models.Q(('seq__gt', 0)), name='revision_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('node', 'seq'), name='revision_seq_unique'),
        ),
    ]
