# Generated by Django 6.1 on 2026-08-12 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0002_invariant_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='node',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='mind.node'),
        ),
    ]
