# Generated by Django 6.1 on 2026-08-12 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0003_alter_activityevent_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('captured', 'Captured'), ('revised', 'Revised'), ('concept_proposed', 'Concept Proposed'), ('concept_confirmed', 'Concept Confirmed'), ('alias_merged', 'Alias Merged'), ('mention_proposed', 'Mention Proposed'), ('mention_confirmed', 'Mention Confirmed'), ('edge_created', 'Edge Created'), ('edge_removed', 'Edge Removed'), ('hypothesis_proposed', 'Hypothesis Proposed'), ('hypothesis_surfaced', 'Hypothesis Surfaced'), ('hypothesis_resolved', 'Hypothesis Resolved'), ('thread_articulated', 'Thread Articulated'), ('reviewed', 'Reviewed'), ('imported', 'Imported'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('purged', 'Purged')], max_length=32),
        ),
        migrations.AlterField(
            model_name='node',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('share', 'Share'), ('import', 'Import'), ('api', 'Api'), ('thread', 'Thread')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['captured', 'revised', 'concept_proposed', 'concept_confirmed', 'alias_merged', 'mention_proposed', 'mention_confirmed', 'edge_created', 'edge_removed', 'hypothesis_proposed', 'hypothesis_surfaced', 'hypothesis_resolved', 'thread_articulated', 'reviewed', 'imported', 'archived', 'deleted', 'purged'])), name='event_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='conceptcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('concept_type__in', ['person', 'place', 'object', 'project', 'activity', 'motif'])), name='concept_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='connectionhypothesis',
            constraint=models.CheckConstraint(condition=models.Q(('relation__isnull', True), ('relation__in', ['relates_to', 'answers', 'member_of', 'contradicts', 'supersedes', 'developed_from']), _connector='OR'), name='hypothesis_relation_valid'),
        ),
        migrations.AddConstraint(
            model_name='connectionhypothesis',
            constraint=models.CheckConstraint(condition=models.Q(('resolution__isnull', True), ('resolution__in', ['confirmed', 'dismissed', 'expired', 'renamed']), _connector='OR'), name='hypothesis_resolution_valid'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('relation__in', ['relates_to', 'answers', 'member_of', 'contradicts', 'supersedes', 'developed_from'])), name='edge_relation_valid'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['explicit', 'inferred'])), name='edge_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['explicit', 'inferred'])), name='mention_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['web', 'mobile', 'share', 'import', 'api', 'thread'])), name='node_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='retrievalmiss',
            constraint=models.CheckConstraint(condition=models.Q(('context__in', ['search', 'capture'])), name='miss_context_valid'),
        ),
    ]
