# Generated by Django 6.1 on 2026-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0004_alter_activityevent_event_type_alter_node_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhypothesis',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='retrievalmiss',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
