# Generated by Django 6.1 on 2026-08-13 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0005_alter_connectionhypothesis_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conceptcandidate',
            name='concept_type_valid',
        ),
        migrations.AlterField(
            model_name='conceptcandidate',
            name='concept_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('person', 'Person'), ('place', 'Place'), ('object', 'Object'), ('project', 'Project'), ('activity', 'Activity'), ('motif', 'Motif')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='conceptcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('concept_type__in', ['unknown', 'person', 'place', 'object', 'project', 'activity', 'motif'])), name='concept_type_valid'),
        ),
    ]
