# Generated by Django 6.1 on 2026-08-13 00:27

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0006_remove_conceptcandidate_concept_type_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='node',
            name='node_search_original',
        ),
        migrations.RemoveIndex(
            model_name='revision',
            name='revision_search_body',
        ),
        migrations.AddIndex(
            model_name='node',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_original'], name='node_search_original'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_body'], name='revision_search_body'),
        ),
    ]
