# Generated by Django 6.1 on 2026-08-13 01:08

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0007_remove_node_node_search_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('span_start', models.PositiveIntegerField()),
                ('span_end', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('index_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_embeddings', to='mind.node')),
            ],
            options={
                'indexes': [models.Index(fields=['index_version'], name='sentence_by_model'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='sentence_vector_hnsw', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('node', 'index_version', 'seq'), name='sentence_unique_per_model'), models.CheckConstraint(condition=models.Q(('span_end__gt', models.F('span_start'))), name='sentence_span_ordered')],
            },
        ),
    ]
