# Generated by Django 5.2.17 on 2026-08-14 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0009_apitoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activityevent',
            name='event_type_valid',
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('captured', 'Captured'), ('revised', 'Revised'), ('concept_proposed', 'Concept Proposed'), ('concept_confirmed', 'Concept Confirmed'), ('concept_retired', 'Concept Retired'), ('alias_merged', 'Alias Merged'), ('mention_proposed', 'Mention Proposed'), ('mention_confirmed', 'Mention Confirmed'), ('edge_created', 'Edge Created'), ('edge_removed', 'Edge Removed'), ('hypothesis_proposed', 'Hypothesis Proposed'), ('hypothesis_surfaced', 'Hypothesis Surfaced'), ('hypothesis_resolved', 'Hypothesis Resolved'), ('thread_articulated', 'Thread Articulated'), ('reviewed', 'Reviewed'), ('imported', 'Imported'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('purged', 'Purged')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['captured', 'revised', 'concept_proposed', 'concept_confirmed', 'concept_retired', 'alias_merged', 'mention_proposed', 'mention_confirmed', 'edge_created', 'edge_removed', 'hypothesis_proposed', 'hypothesis_surfaced', 'hypothesis_resolved', 'thread_articulated', 'reviewed', 'imported', 'archived', 'deleted', 'purged'])), name='event_type_valid'),
        ),
    ]
