# Generated by Django 5.2.16 on 2026-08-14 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0034_remove_item_project_remove_project_area'),
        ('mind', '0010_concept_retired_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('actionable', 'Actionable'), ('media', 'Media'), ('goal', 'Goal'), ('epistemic', 'Epistemic status'), ('concept', 'Concept')], max_length=16)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('origin', models.CharField(choices=[('explicit', 'Explicit'), ('inferred', 'Inferred')], max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='activityevent',
            name='event_type_valid',
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('captured', 'Captured'), ('revised', 'Revised'), ('concept_proposed', 'Concept Proposed'), ('concept_confirmed', 'Concept Confirmed'), ('concept_retired', 'Concept Retired'), ('facet_proposed', 'Facet Proposed'), ('facet_confirmed', 'Facet Confirmed'), ('alias_merged', 'Alias Merged'), ('mention_proposed', 'Mention Proposed'), ('mention_confirmed', 'Mention Confirmed'), ('edge_created', 'Edge Created'), ('edge_removed', 'Edge Removed'), ('hypothesis_proposed', 'Hypothesis Proposed'), ('hypothesis_surfaced', 'Hypothesis Surfaced'), ('hypothesis_resolved', 'Hypothesis Resolved'), ('thread_articulated', 'Thread Articulated'), ('reviewed', 'Reviewed'), ('imported', 'Imported'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('purged', 'Purged')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['captured', 'revised', 'concept_proposed', 'concept_confirmed', 'concept_retired', 'facet_proposed', 'facet_confirmed', 'alias_merged', 'mention_proposed', 'mention_confirmed', 'edge_created', 'edge_removed', 'hypothesis_proposed', 'hypothesis_surfaced', 'hypothesis_resolved', 'thread_articulated', 'reviewed', 'imported', 'archived', 'deleted', 'purged'])), name='event_type_valid'),
        ),
        migrations.AddField(
            model_name='facet',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facets', to='mind.node'),
        ),
        migrations.AddField(
            model_name='facet',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mind_facets', to='lists.item'),
        ),
        migrations.AddIndex(
            model_name='facet',
            index=models.Index(fields=['node', 'kind'], name='mind_facet_node_id_682e74_idx'),
        ),
        migrations.AddConstraint(
            model_name='facet',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['actionable', 'media', 'goal', 'epistemic', 'concept'])), name='facet_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='facet',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['explicit', 'inferred'])), name='facet_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='facet',
            constraint=models.UniqueConstraint(condition=models.Q(('retired_at__isnull', True)), fields=('node', 'kind'), name='facet_one_live_per_kind'),
        ),
    ]
