# Generated by Django 5.2.16 on 2026-08-19 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_dailyfocus'),
        ('lists', '0038_project_purpose'),
        ('mind', '0015_erasure_exemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='facet',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facets', to='daily.dailyentry'),
        ),
        migrations.AddField(
            model_name='facet',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='facet',
            name='span_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facet',
            name='span_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facet',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facets', to='mind.node'),
        ),
        migrations.AddIndex(
            model_name='facet',
            index=models.Index(fields=['entry', 'kind'], name='facet_by_entry'),
        ),
        migrations.AddConstraint(
            model_name='facet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry__isnull', True), ('node__isnull', False)), models.Q(('entry__isnull', False), ('node__isnull', True)), _connector='OR'), name='facet_cites_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='facet',
            constraint=models.UniqueConstraint(fields=('entry', 'fingerprint'), name='facet_entry_fingerprint_unique'),
        ),
        migrations.AddConstraint(
            model_name='facet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('span_end__isnull', True), ('span_start__isnull', True)), models.Q(('span_end__isnull', False), ('span_start__isnull', False)), _connector='OR'), name='facet_span_paired'),
        ),
        migrations.AddConstraint(
            model_name='facet',
            constraint=models.CheckConstraint(condition=models.Q(('span_start__isnull', True), ('span_end__gt', models.F('span_start')), _connector='OR'), name='facet_span_ordered'),
        ),
    ]
