# Generated by Django 5.2.16 on 2026-08-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0016_facet_entry_facet_fingerprint_facet_span_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facet',
            name='producer',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
    ]
