# Generated by Django 5.2.16 on 2026-08-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0017_facet_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievalmiss',
            name='days_found',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retrievalmiss',
            name='notes_found',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retrievalmiss',
            name='tasks_found',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
