# Generated by Django 5.2.16 on 2026-08-21 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_dailyfocus_accepted_from_draft'),
        ('lists', '0044_item_lead_days_recurringcommitment_lead_days'),
        ('mind', '0018_retrievalmiss_days_found_retrievalmiss_notes_found_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activityevent',
            name='event_type_valid',
        ),
        migrations.AddField(
            model_name='activityevent',
            name='entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='daily.dailyentry'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='lists.item'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('captured', 'Captured'), ('revised', 'Revised'), ('concept_proposed', 'Concept Proposed'), ('concept_confirmed', 'Concept Confirmed'), ('concept_retired', 'Concept Retired'), ('facet_proposed', 'Facet Proposed'), ('facet_confirmed', 'Facet Confirmed'), ('facet_dismissed', 'Facet Dismissed'), ('alias_merged', 'Alias Merged'), ('mention_proposed', 'Mention Proposed'), ('mention_confirmed', 'Mention Confirmed'), ('edge_created', 'Edge Created'), ('edge_removed', 'Edge Removed'), ('hypothesis_proposed', 'Hypothesis Proposed'), ('hypothesis_surfaced', 'Hypothesis Surfaced'), ('hypothesis_resolved', 'Hypothesis Resolved'), ('thread_articulated', 'Thread Articulated'), ('reviewed', 'Reviewed'), ('imported', 'Imported'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('purged', 'Purged'), ('maintenance_ran', 'Maintenance Ran'), ('task_completed', 'Task Completed'), ('task_reopened', 'Task Reopened'), ('task_archived', 'Task Archived'), ('commitment_changed', 'Commitment Changed'), ('commitment_ended', 'Commitment Ended'), ('focus_pinned', 'Focus Pinned'), ('focus_released', 'Focus Released'), ('week_reviewed', 'Week Reviewed'), ('intention_set', 'Intention Set'), ('outcome_chosen', 'Outcome Chosen')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['task', 'event_type', 'occurred_at'], name='event_by_task'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['entry', 'event_type', 'occurred_at'], name='event_by_entry'),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['captured', 'revised', 'concept_proposed', 'concept_confirmed', 'concept_retired', 'facet_proposed', 'facet_confirmed', 'facet_dismissed', 'alias_merged', 'mention_proposed', 'mention_confirmed', 'edge_created', 'edge_removed', 'hypothesis_proposed', 'hypothesis_surfaced', 'hypothesis_resolved', 'thread_articulated', 'reviewed', 'imported', 'archived', 'deleted', 'purged', 'maintenance_ran', 'task_completed', 'task_reopened', 'task_archived', 'commitment_changed', 'commitment_ended', 'focus_pinned', 'focus_released', 'week_reviewed', 'intention_set', 'outcome_chosen'])), name='event_type_valid'),
        ),
    ]
