# Generated by Django 5.2.16 on 2026-08-21 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_dailyfocus_accepted_from_draft'),
        ('lists', '0044_item_lead_days_recurringcommitment_lead_days'),
        ('mind', '0019_remove_activityevent_event_type_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='origin',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('reconstructed', 'Reconstructed')], default='recorded', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['recorded', 'reconstructed'])), name='event_origin_valid'),
        ),
    ]
