# Generated by Django 5.2.16 on 2026-08-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_dailyfocus_accepted_from_draft'),
        ('lists', '0044_item_lead_days_recurringcommitment_lead_days'),
        ('mind', '0020_activityevent_origin_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facet',
            name='facet_kind_valid',
        ),
        migrations.AlterField(
            model_name='facet',
            name='kind',
            field=models.CharField(choices=[('actionable', 'Actionable'), ('recipe', 'Recipe or procedure'), ('occasion', 'Occasion or birthday'), ('dream', 'Dream'), ('fear', 'Fear'), ('desire', 'Something I want'), ('preference', 'Preference'), ('media', 'Media'), ('goal', 'Goal'), ('epistemic', 'Epistemic status'), ('concept', 'Concept')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='facet',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['actionable', 'recipe', 'occasion', 'dream', 'fear', 'desire', 'preference', 'media', 'goal', 'epistemic', 'concept'])), name='facet_kind_valid'),
        ),
    ]
