# Generated by Django 5.2.16 on 2026-08-22 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0021_remove_facet_facet_kind_valid_alter_facet_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retrievalmiss',
            name='miss_context_valid',
        ),
        migrations.AlterField(
            model_name='retrievalmiss',
            name='context',
            field=models.CharField(choices=[('search', 'Search'), ('capture', 'Capture'), ('recollection', 'Recollection')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='retrievalmiss',
            constraint=models.CheckConstraint(condition=models.Q(('context__in', ['search', 'capture', 'recollection'])), name='miss_context_valid'),
        ),
    ]
