# Generated by Django 5.2.16 on 2026-08-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0024_capturesession_node_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='storage_key',
        ),
        migrations.AddField(
            model_name='attachment',
            name='content',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('content', b''), _negated=True), name='attachment_has_content'),
        ),
    ]
