# Generated by Django 5.2.16 on 2026-08-22 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0025_remove_attachment_storage_key_attachment_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.TextField()),
                ('url', models.TextField(blank=True, default='')),
                ('author', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='node',
            name='came_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='mind.source'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(('url', ''), _negated=True), fields=('owner', 'url'), name='source_url_unique_per_owner'),
        ),
    ]
