# Generated by Django 5.2.16 on 2026-08-22 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0026_source_node_came_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.TextField()),
                ('chose', models.TextField()),
                ('considered', models.TextField(blank=True, default='')),
                ('revisit_when', models.TextField(blank=True, default='')),
                ('revisit_after', models.DateField(blank=True, null=True)),
                ('decided_at', models.DateTimeField()),
                ('revisited_at', models.DateTimeField(blank=True, null=True)),
                ('cited_text', models.TextField(blank=True, default='')),
                ('cited_revision_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('cited_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='mind.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='mind.decision')),
            ],
            options={
                'ordering': ('-decided_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('chose', ''), _negated=True), name='decision_chose_something')],
            },
        ),
    ]
