# Generated by Django 5.2.17 on 2026-09-04 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0005_dailyentry_list_closed_at'),
        ('lists', '0062_item_kept_at'),
        ('mind', '0028_remove_activityevent_event_type_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activityevent',
            name='event_type_valid',
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('captured', 'Captured'), ('revised', 'Revised'), ('concept_proposed', 'Concept Proposed'), ('concept_confirmed', 'Concept Confirmed'), ('concept_retired', 'Concept Retired'), ('facet_proposed', 'Facet Proposed'), ('facet_confirmed', 'Facet Confirmed'), ('facet_dismissed', 'Facet Dismissed'), ('alias_merged', 'Alias Merged'), ('mention_proposed', 'Mention Proposed'), ('mention_confirmed', 'Mention Confirmed'), ('edge_created', 'Edge Created'), ('edge_removed', 'Edge Removed'), ('hypothesis_proposed', 'Hypothesis Proposed'), ('hypothesis_surfaced', 'Hypothesis Surfaced'), ('hypothesis_resolved', 'Hypothesis Resolved'), ('thread_articulated', 'Thread Articulated'), ('reviewed', 'Reviewed'), ('imported', 'Imported'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('purged', 'Purged'), ('maintenance_ran', 'Maintenance Ran'), ('task_completed', 'Task Completed'), ('task_reopened', 'Task Reopened'), ('task_archived', 'Task Archived'), ('commitment_changed', 'Commitment Changed'), ('commitment_ended', 'Commitment Ended'), ('task_let_go', 'Task Let Go'), ('appointment_made', 'Appointment Made'), ('appointment_cancelled', 'Appointment Cancelled'), ('focus_pinned', 'Focus Pinned'), ('focus_released', 'Focus Released'), ('week_reviewed', 'Week Reviewed'), ('intention_set', 'Intention Set'), ('outcome_chosen', 'Outcome Chosen')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['captured', 'revised', 'concept_proposed', 'concept_confirmed', 'concept_retired', 'facet_proposed', 'facet_confirmed', 'facet_dismissed', 'alias_merged', 'mention_proposed', 'mention_confirmed', 'edge_created', 'edge_removed', 'hypothesis_proposed', 'hypothesis_surfaced', 'hypothesis_resolved', 'thread_articulated', 'reviewed', 'imported', 'archived', 'deleted', 'purged', 'maintenance_ran', 'task_completed', 'task_reopened', 'task_archived', 'commitment_changed', 'commitment_ended', 'task_let_go', 'appointment_made', 'appointment_cancelled', 'focus_pinned', 'focus_released', 'week_reviewed', 'intention_set', 'outcome_chosen'])), name='event_type_valid'),
        ),
    ]
